import type { CalendarInsertItem } from "../schema";

export const seedCalendar = [
  {
    title: "Team Picnic",
    description: ["Let's get together and have some food."],
    location: "VA",
    visibleTo: ["students", "mentors", "parents"],
    signupLink: "https://www.fairportcanaldays.com/canal-days/",
    signupLinkVisibleTo: ["students", "mentors", "parents"],
    startAt: new Date("2026-05-17T11:00:00"),
    endAt: new Date("2026-05-17T14:00:00"),
  },
  {
    title: "Chicken BBQ",
    description: ["Our biggest fundraising event of the year!"],
    location: "Fairport Hight School",
    visibleTo: ["students", "mentors", "parents"],
    signupLink:
      "https://docs.google.com/document/d/1_PRVoHSkZooYqhKoe5y_CzNP81IDup8ZX0r8gNaCdyE/edit?tab=t.0",
    signupLinkVisibleTo: ["students", "mentors", "parents"],
    startAt: new Date("2026-06-18T15:00:00"),
    endAt: new Date("2026-06-18T19:30:00"),
  },
  {
    title: "Summer STEM - Session 1",
    description: ["Shape some minds"],
    location: "Perinton Rec Center",
    visibleTo: ["students", "mentors", "parents"],
    signupLink: "https://docs.google.com/document/d/1ywDMMYkyJ2sHhaRnDX1E3wkYxrGx03Q8/edit",
    signupLinkVisibleTo: ["students", "mentors", "parents"],
    startAt: new Date("2026-07-15T17:30:00"),
    endAt: new Date("2026-07-15T20:00:00"),
  },
  {
    title: "Summer STEM - Session 2",
    description: ["Shape some minds"],
    location: "Perinton Rec Center",
    visibleTo: ["students", "mentors", "parents"],
    signupLink: "https://docs.google.com/document/d/1ywDMMYkyJ2sHhaRnDX1E3wkYxrGx03Q8/edit",
    signupLinkVisibleTo: ["students", "mentors", "parents"],
    startAt: new Date("2026-08-11T17:30:00"),
    endAt: new Date("2026-08-11T20:00:00"),
  },
  {
    title: "FLL Info",
    description: ["Shape some minds"],
    location: "Perinton Rec Center",
    visibleTo: ["students", "mentors", "parents"],
    signupLink: "https://docs.google.com/document/d/1ywDMMYkyJ2sHhaRnDX1E3wkYxrGx03Q8/edit",
    signupLinkVisibleTo: ["students", "mentors", "parents"],
    startAt: new Date("2026-08-16T17:30:00"),
    endAt: new Date("2026-08-16T19:45:00"),
  },
  {
    title: "Canal Days",
    description: [
      "Stop by and visit us at the Fairport Canal Days for STEM fun and games.",
      "Let the kids play catch with one of our competition robots.",
      "Our booth with also have lots of inreresting bits and bobs so kids can make their very own Junk Bots.",
    ],
    location: "Fairport Village",
    visibleTo: ["everyone"],
    informationLink: "https://www.fairportcanaldays.com/canal-days/",
    startAt: new Date("2026-06-06T08:00:00"),
    endAt: new Date("2026-06-07T17:00:00"),
  },
  {
    title: "Mentor Meeting",
    description: [
      "Mentors - please join us for the end of the year review and discussion on plans for next year.",
    ],
    location: "Minerva Deland",
    visibleTo: ["mentors"],
    informationLink: "https://www.fairportcanaldays.com/canal-days/",
    startAt: new Date("2026-05-26T18:00:00"),
    endAt: new Date("2026-06-26T20:00:00"),
  },
] as CalendarInsertItem[];
