/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as UnauthenticatedContactRouteImport } from './routes/_unauthenticated/contact'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as UnauthenticatedTeamIndexRouteImport } from './routes/_unauthenticated/team/index'
import { Route as UnauthenticatedSponsorsIndexRouteImport } from './routes/_unauthenticated/sponsors/index'
import { Route as UnauthenticatedGamesIndexRouteImport } from './routes/_unauthenticated/games/index'
import { Route as UnauthenticatedCalendarIndexRouteImport } from './routes/_unauthenticated/calendar/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UnauthenticatedTeamIdRouteImport } from './routes/_unauthenticated/team/$id'
import { Route as UnauthenticatedGamesIdRouteImport } from './routes/_unauthenticated/games/$id'
import { Route as AuthenticatedAdminSponsorsRouteImport } from './routes/_authenticated/admin/sponsors'
import { Route as AuthenticatedAdminGamesRouteImport } from './routes/_authenticated/admin/games'
import { Route as UnauthenticatedCalendarIdIndexRouteImport } from './routes/_unauthenticated/calendar/$id/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminCalendarIndexRouteImport } from './routes/_authenticated/admin/calendar/index'
import { Route as AuthenticatedAdminCalendarNewRouteImport } from './routes/_authenticated/admin/calendar/new'
import { Route as AuthenticatedAdminUsersUserIdRouteRouteImport } from './routes/_authenticated/admin/users/$userId/route'
import { Route as AuthenticatedAdminUsersUserIdIndexRouteImport } from './routes/_authenticated/admin/users/$userId/index'
import { Route as AuthenticatedAdminCalendarIdIndexRouteImport } from './routes/_authenticated/admin/calendar/$id/index'
import { Route as AuthenticatedAdminUsersUserIdEditRouteImport } from './routes/_authenticated/admin/users/$userId/edit'
import { Route as AuthenticatedAdminCalendarIdPublishedRouteImport } from './routes/_authenticated/admin/calendar/$id/published'
import { Route as AuthenticatedAdminCalendarIdDraftRouteImport } from './routes/_authenticated/admin/calendar/$id/draft'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const UnauthenticatedContactRoute = UnauthenticatedContactRouteImport.update({
  id: '/_unauthenticated/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedTeamIndexRoute =
  UnauthenticatedTeamIndexRouteImport.update({
    id: '/_unauthenticated/team/',
    path: '/team/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedSponsorsIndexRoute =
  UnauthenticatedSponsorsIndexRouteImport.update({
    id: '/_unauthenticated/sponsors/',
    path: '/sponsors/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedGamesIndexRoute =
  UnauthenticatedGamesIndexRouteImport.update({
    id: '/_unauthenticated/games/',
    path: '/games/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedCalendarIndexRoute =
  UnauthenticatedCalendarIndexRouteImport.update({
    id: '/_unauthenticated/calendar/',
    path: '/calendar/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/_authenticated/profile/',
    path: '/profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedTeamIdRoute = UnauthenticatedTeamIdRouteImport.update({
  id: '/_unauthenticated/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedGamesIdRoute = UnauthenticatedGamesIdRouteImport.update({
  id: '/_unauthenticated/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSponsorsRoute =
  AuthenticatedAdminSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGamesRoute = AuthenticatedAdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const UnauthenticatedCalendarIdIndexRoute =
  UnauthenticatedCalendarIdIndexRouteImport.update({
    id: '/_unauthenticated/calendar/$id/',
    path: '/calendar/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarIndexRoute =
  AuthenticatedAdminCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarNewRoute =
  AuthenticatedAdminCalendarNewRouteImport.update({
    id: '/calendar/new',
    path: '/calendar/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRouteRoute =
  AuthenticatedAdminUsersUserIdRouteRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRouteRoute,
  } as any)
const AuthenticatedAdminCalendarIdIndexRoute =
  AuthenticatedAdminCalendarIdIndexRouteImport.update({
    id: '/calendar/$id/',
    path: '/calendar/$id/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdEditRoute =
  AuthenticatedAdminUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRouteRoute,
  } as any)
const AuthenticatedAdminCalendarIdPublishedRoute =
  AuthenticatedAdminCalendarIdPublishedRouteImport.update({
    id: '/calendar/$id/published',
    path: '/calendar/$id/published',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarIdDraftRoute =
  AuthenticatedAdminCalendarIdDraftRouteImport.update({
    id: '/calendar/$id/draft',
    path: '/calendar/$id/draft',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/contact': typeof UnauthenticatedContactRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/games': typeof AuthenticatedAdminGamesRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/games/$id': typeof UnauthenticatedGamesIdRoute
  '/team/$id': typeof UnauthenticatedTeamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/calendar/': typeof UnauthenticatedCalendarIndexRoute
  '/games/': typeof UnauthenticatedGamesIndexRoute
  '/sponsors/': typeof UnauthenticatedSponsorsIndexRoute
  '/team/': typeof UnauthenticatedTeamIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteRouteWithChildren
  '/admin/calendar/new': typeof AuthenticatedAdminCalendarNewRoute
  '/admin/calendar/': typeof AuthenticatedAdminCalendarIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/calendar/$id/': typeof UnauthenticatedCalendarIdIndexRoute
  '/admin/calendar/$id/draft': typeof AuthenticatedAdminCalendarIdDraftRoute
  '/admin/calendar/$id/published': typeof AuthenticatedAdminCalendarIdPublishedRoute
  '/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
  '/admin/calendar/$id/': typeof AuthenticatedAdminCalendarIdIndexRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/contact': typeof UnauthenticatedContactRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/games': typeof AuthenticatedAdminGamesRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/games/$id': typeof UnauthenticatedGamesIdRoute
  '/team/$id': typeof UnauthenticatedTeamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/calendar': typeof UnauthenticatedCalendarIndexRoute
  '/games': typeof UnauthenticatedGamesIndexRoute
  '/sponsors': typeof UnauthenticatedSponsorsIndexRoute
  '/team': typeof UnauthenticatedTeamIndexRoute
  '/admin/calendar/new': typeof AuthenticatedAdminCalendarNewRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/calendar/$id': typeof UnauthenticatedCalendarIdIndexRoute
  '/admin/calendar/$id/draft': typeof AuthenticatedAdminCalendarIdDraftRoute
  '/admin/calendar/$id/published': typeof AuthenticatedAdminCalendarIdPublishedRoute
  '/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
  '/admin/calendar/$id': typeof AuthenticatedAdminCalendarIdIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_unauthenticated/contact': typeof UnauthenticatedContactRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/admin/games': typeof AuthenticatedAdminGamesRoute
  '/_authenticated/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/_unauthenticated/games/$id': typeof UnauthenticatedGamesIdRoute
  '/_unauthenticated/team/$id': typeof UnauthenticatedTeamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_unauthenticated/calendar/': typeof UnauthenticatedCalendarIndexRoute
  '/_unauthenticated/games/': typeof UnauthenticatedGamesIndexRoute
  '/_unauthenticated/sponsors/': typeof UnauthenticatedSponsorsIndexRoute
  '/_unauthenticated/team/': typeof UnauthenticatedTeamIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteRouteWithChildren
  '/_authenticated/admin/calendar/new': typeof AuthenticatedAdminCalendarNewRoute
  '/_authenticated/admin/calendar/': typeof AuthenticatedAdminCalendarIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_unauthenticated/calendar/$id/': typeof UnauthenticatedCalendarIdIndexRoute
  '/_authenticated/admin/calendar/$id/draft': typeof AuthenticatedAdminCalendarIdDraftRoute
  '/_authenticated/admin/calendar/$id/published': typeof AuthenticatedAdminCalendarIdPublishedRoute
  '/_authenticated/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
  '/_authenticated/admin/calendar/$id/': typeof AuthenticatedAdminCalendarIdIndexRoute
  '/_authenticated/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthenticated'
    | '/unauthorized'
    | '/admin'
    | '/contact'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/games'
    | '/admin/sponsors'
    | '/games/$id'
    | '/team/$id'
    | '/api/auth/$'
    | '/admin/'
    | '/profile/'
    | '/calendar/'
    | '/games/'
    | '/sponsors/'
    | '/team/'
    | '/admin/users/$userId'
    | '/admin/calendar/new'
    | '/admin/calendar/'
    | '/admin/users/'
    | '/calendar/$id/'
    | '/admin/calendar/$id/draft'
    | '/admin/calendar/$id/published'
    | '/admin/users/$userId/edit'
    | '/admin/calendar/$id/'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unauthenticated'
    | '/unauthorized'
    | '/contact'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/games'
    | '/admin/sponsors'
    | '/games/$id'
    | '/team/$id'
    | '/api/auth/$'
    | '/admin'
    | '/profile'
    | '/calendar'
    | '/games'
    | '/sponsors'
    | '/team'
    | '/admin/calendar/new'
    | '/admin/calendar'
    | '/admin/users'
    | '/calendar/$id'
    | '/admin/calendar/$id/draft'
    | '/admin/calendar/$id/published'
    | '/admin/users/$userId/edit'
    | '/admin/calendar/$id'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/unauthenticated'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_unauthenticated/contact'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/_authenticated/admin/games'
    | '/_authenticated/admin/sponsors'
    | '/_unauthenticated/games/$id'
    | '/_unauthenticated/team/$id'
    | '/api/auth/$'
    | '/_authenticated/admin/'
    | '/_authenticated/profile/'
    | '/_unauthenticated/calendar/'
    | '/_unauthenticated/games/'
    | '/_unauthenticated/sponsors/'
    | '/_unauthenticated/team/'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/admin/calendar/new'
    | '/_authenticated/admin/calendar/'
    | '/_authenticated/admin/users/'
    | '/_unauthenticated/calendar/$id/'
    | '/_authenticated/admin/calendar/$id/draft'
    | '/_authenticated/admin/calendar/$id/published'
    | '/_authenticated/admin/users/$userId/edit'
    | '/_authenticated/admin/calendar/$id/'
    | '/_authenticated/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  UnauthenticatedContactRoute: typeof UnauthenticatedContactRoute
  UnauthenticatedGamesIdRoute: typeof UnauthenticatedGamesIdRoute
  UnauthenticatedTeamIdRoute: typeof UnauthenticatedTeamIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  UnauthenticatedCalendarIndexRoute: typeof UnauthenticatedCalendarIndexRoute
  UnauthenticatedGamesIndexRoute: typeof UnauthenticatedGamesIndexRoute
  UnauthenticatedSponsorsIndexRoute: typeof UnauthenticatedSponsorsIndexRoute
  UnauthenticatedTeamIndexRoute: typeof UnauthenticatedTeamIndexRoute
  UnauthenticatedCalendarIdIndexRoute: typeof UnauthenticatedCalendarIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_unauthenticated/contact': {
      id: '/_unauthenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof UnauthenticatedContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/team/': {
      id: '/_unauthenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof UnauthenticatedTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/sponsors/': {
      id: '/_unauthenticated/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof UnauthenticatedSponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/games/': {
      id: '/_unauthenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof UnauthenticatedGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/calendar/': {
      id: '/_unauthenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof UnauthenticatedCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/team/$id': {
      id: '/_unauthenticated/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof UnauthenticatedTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/games/$id': {
      id: '/_unauthenticated/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof UnauthenticatedGamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/sponsors': {
      id: '/_authenticated/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/games': {
      id: '/_authenticated/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AuthenticatedAdminGamesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_unauthenticated/calendar/$id/': {
      id: '/_unauthenticated/calendar/$id/'
      path: '/calendar/$id'
      fullPath: '/calendar/$id/'
      preLoaderRoute: typeof UnauthenticatedCalendarIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar/': {
      id: '/_authenticated/admin/calendar/'
      path: '/calendar'
      fullPath: '/admin/calendar/'
      preLoaderRoute: typeof AuthenticatedAdminCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar/new': {
      id: '/_authenticated/admin/calendar/new'
      path: '/calendar/new'
      fullPath: '/admin/calendar/new'
      preLoaderRoute: typeof AuthenticatedAdminCalendarNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$userId/': {
      id: '/_authenticated/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteRoute
    }
    '/_authenticated/admin/calendar/$id/': {
      id: '/_authenticated/admin/calendar/$id/'
      path: '/calendar/$id'
      fullPath: '/admin/calendar/$id/'
      preLoaderRoute: typeof AuthenticatedAdminCalendarIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$userId/edit': {
      id: '/_authenticated/admin/users/$userId/edit'
      path: '/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteRoute
    }
    '/_authenticated/admin/calendar/$id/published': {
      id: '/_authenticated/admin/calendar/$id/published'
      path: '/calendar/$id/published'
      fullPath: '/admin/calendar/$id/published'
      preLoaderRoute: typeof AuthenticatedAdminCalendarIdPublishedRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar/$id/draft': {
      id: '/_authenticated/admin/calendar/$id/draft'
      path: '/calendar/$id/draft'
      fullPath: '/admin/calendar/$id/draft'
      preLoaderRoute: typeof AuthenticatedAdminCalendarIdDraftRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedAdminUsersUserIdRouteRouteChildren {
  AuthenticatedAdminUsersUserIdEditRoute: typeof AuthenticatedAdminUsersUserIdEditRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteRouteChildren: AuthenticatedAdminUsersUserIdRouteRouteChildren =
  {
    AuthenticatedAdminUsersUserIdEditRoute:
      AuthenticatedAdminUsersUserIdEditRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteRouteWithChildren =
  AuthenticatedAdminUsersUserIdRouteRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminGamesRoute: typeof AuthenticatedAdminGamesRoute
  AuthenticatedAdminSponsorsRoute: typeof AuthenticatedAdminSponsorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRouteRoute: typeof AuthenticatedAdminUsersUserIdRouteRouteWithChildren
  AuthenticatedAdminCalendarNewRoute: typeof AuthenticatedAdminCalendarNewRoute
  AuthenticatedAdminCalendarIndexRoute: typeof AuthenticatedAdminCalendarIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminCalendarIdDraftRoute: typeof AuthenticatedAdminCalendarIdDraftRoute
  AuthenticatedAdminCalendarIdPublishedRoute: typeof AuthenticatedAdminCalendarIdPublishedRoute
  AuthenticatedAdminCalendarIdIndexRoute: typeof AuthenticatedAdminCalendarIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminGamesRoute: AuthenticatedAdminGamesRoute,
    AuthenticatedAdminSponsorsRoute: AuthenticatedAdminSponsorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUsersUserIdRouteRoute:
      AuthenticatedAdminUsersUserIdRouteRouteWithChildren,
    AuthenticatedAdminCalendarNewRoute: AuthenticatedAdminCalendarNewRoute,
    AuthenticatedAdminCalendarIndexRoute: AuthenticatedAdminCalendarIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
    AuthenticatedAdminCalendarIdDraftRoute:
      AuthenticatedAdminCalendarIdDraftRoute,
    AuthenticatedAdminCalendarIdPublishedRoute:
      AuthenticatedAdminCalendarIdPublishedRoute,
    AuthenticatedAdminCalendarIdIndexRoute:
      AuthenticatedAdminCalendarIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  UnauthenticatedContactRoute: UnauthenticatedContactRoute,
  UnauthenticatedGamesIdRoute: UnauthenticatedGamesIdRoute,
  UnauthenticatedTeamIdRoute: UnauthenticatedTeamIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  UnauthenticatedCalendarIndexRoute: UnauthenticatedCalendarIndexRoute,
  UnauthenticatedGamesIndexRoute: UnauthenticatedGamesIndexRoute,
  UnauthenticatedSponsorsIndexRoute: UnauthenticatedSponsorsIndexRoute,
  UnauthenticatedTeamIndexRoute: UnauthenticatedTeamIndexRoute,
  UnauthenticatedCalendarIdIndexRoute: UnauthenticatedCalendarIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
