/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamIdRouteImport } from './routes/team/$id'
import { Route as GamesIdRouteImport } from './routes/games/$id'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminSponsorsRouteImport } from './routes/admin/sponsors'
import { Route as AdminGamesRouteImport } from './routes/admin/games'
import { Route as CalendarIdIndexRouteImport } from './routes/calendar/$id/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminCalendarIndexRouteImport } from './routes/admin/calendar/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminCalendarTestRouteImport } from './routes/admin/calendar/test'
import { Route as AdminUsersUserIdRouteRouteImport } from './routes/admin/users/$userId/route'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminCalendarIdIndexRouteImport } from './routes/admin/calendar/$id/index'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'
import { Route as AdminCalendarIdEditRouteImport } from './routes/admin/calendar/$id/edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CalendarIdIndexRoute = CalendarIdIndexRouteImport.update({
  id: '/calendar/$id/',
  path: '/calendar/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarIndexRoute = AdminCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarTestRoute = AdminCalendarTestRouteImport.update({
  id: '/calendar/test',
  path: '/calendar/test',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRouteRoute = AdminUsersUserIdRouteRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersUserIdRouteRoute,
} as any)
const AdminCalendarIdIndexRoute = AdminCalendarIdIndexRouteImport.update({
  id: '/calendar/$id/',
  path: '/calendar/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminUsersUserIdRouteRoute,
} as any)
const AdminCalendarIdEditRoute = AdminCalendarIdEditRouteImport.update({
  id: '/calendar/$id/edit',
  path: '/calendar/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/games/$id': typeof GamesIdRoute
  '/team/$id': typeof TeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/games/': typeof GamesIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteRouteWithChildren
  '/admin/calendar/test': typeof AdminCalendarTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/calendar/': typeof AdminCalendarIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/calendar/$id/': typeof CalendarIdIndexRoute
  '/admin/calendar/$id/edit': typeof AdminCalendarIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/calendar/$id/': typeof AdminCalendarIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/games/$id': typeof GamesIdRoute
  '/team/$id': typeof TeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/games': typeof GamesIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/team': typeof TeamIndexRoute
  '/admin/calendar/test': typeof AdminCalendarTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/calendar': typeof AdminCalendarIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/calendar/$id': typeof CalendarIdIndexRoute
  '/admin/calendar/$id/edit': typeof AdminCalendarIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/calendar/$id': typeof AdminCalendarIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/games/$id': typeof GamesIdRoute
  '/team/$id': typeof TeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/games/': typeof GamesIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteRouteWithChildren
  '/admin/calendar/test': typeof AdminCalendarTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/calendar/': typeof AdminCalendarIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/calendar/$id/': typeof CalendarIdIndexRoute
  '/admin/calendar/$id/edit': typeof AdminCalendarIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/calendar/$id/': typeof AdminCalendarIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/unauthenticated'
    | '/unauthorized'
    | '/admin/games'
    | '/admin/sponsors'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/games/$id'
    | '/team/$id'
    | '/admin/'
    | '/calendar/'
    | '/games/'
    | '/sponsors/'
    | '/team/'
    | '/admin/users/$userId'
    | '/admin/calendar/test'
    | '/api/auth/$'
    | '/admin/calendar/'
    | '/admin/users/'
    | '/calendar/$id/'
    | '/admin/calendar/$id/edit'
    | '/admin/users/$userId/edit'
    | '/admin/calendar/$id/'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/unauthenticated'
    | '/unauthorized'
    | '/admin/games'
    | '/admin/sponsors'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/games/$id'
    | '/team/$id'
    | '/admin'
    | '/calendar'
    | '/games'
    | '/sponsors'
    | '/team'
    | '/admin/calendar/test'
    | '/api/auth/$'
    | '/admin/calendar'
    | '/admin/users'
    | '/calendar/$id'
    | '/admin/calendar/$id/edit'
    | '/admin/users/$userId/edit'
    | '/admin/calendar/$id'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/unauthenticated'
    | '/unauthorized'
    | '/admin/games'
    | '/admin/sponsors'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/games/$id'
    | '/team/$id'
    | '/admin/'
    | '/calendar/'
    | '/games/'
    | '/sponsors/'
    | '/team/'
    | '/admin/users/$userId'
    | '/admin/calendar/test'
    | '/api/auth/$'
    | '/admin/calendar/'
    | '/admin/users/'
    | '/calendar/$id/'
    | '/admin/calendar/$id/edit'
    | '/admin/users/$userId/edit'
    | '/admin/calendar/$id/'
    | '/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  GamesIdRoute: typeof GamesIdRoute
  TeamIdRoute: typeof TeamIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CalendarIdIndexRoute: typeof CalendarIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/calendar/$id/': {
      id: '/calendar/$id/'
      path: '/calendar/$id'
      fullPath: '/calendar/$id/'
      preLoaderRoute: typeof CalendarIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar/': {
      id: '/admin/calendar/'
      path: '/calendar'
      fullPath: '/admin/calendar/'
      preLoaderRoute: typeof AdminCalendarIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar/test': {
      id: '/admin/calendar/test'
      path: '/calendar/test'
      fullPath: '/admin/calendar/test'
      preLoaderRoute: typeof AdminCalendarTestRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/calendar/$id/': {
      id: '/admin/calendar/$id/'
      path: '/calendar/$id'
      fullPath: '/admin/calendar/$id/'
      preLoaderRoute: typeof AdminCalendarIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/calendar/$id/edit': {
      id: '/admin/calendar/$id/edit'
      path: '/calendar/$id/edit'
      fullPath: '/admin/calendar/$id/edit'
      preLoaderRoute: typeof AdminCalendarIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminUsersUserIdRouteRouteChildren {
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminUsersUserIdRouteRouteChildren: AdminUsersUserIdRouteRouteChildren = {
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminUsersUserIdRouteRouteWithChildren =
  AdminUsersUserIdRouteRoute._addFileChildren(
    AdminUsersUserIdRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminGamesRoute: typeof AdminGamesRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRouteRoute: typeof AdminUsersUserIdRouteRouteWithChildren
  AdminCalendarTestRoute: typeof AdminCalendarTestRoute
  AdminCalendarIndexRoute: typeof AdminCalendarIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminCalendarIdEditRoute: typeof AdminCalendarIdEditRoute
  AdminCalendarIdIndexRoute: typeof AdminCalendarIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminGamesRoute: AdminGamesRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRouteRoute: AdminUsersUserIdRouteRouteWithChildren,
  AdminCalendarTestRoute: AdminCalendarTestRoute,
  AdminCalendarIndexRoute: AdminCalendarIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminCalendarIdEditRoute: AdminCalendarIdEditRoute,
  AdminCalendarIdIndexRoute: AdminCalendarIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  GamesIdRoute: GamesIdRoute,
  TeamIdRoute: TeamIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CalendarIdIndexRoute: CalendarIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
